(function (global) {
  const BOSS_PROFILES = [
    {
      id: 'boss_qing_teng',
      name: '青藤古灵',
      realm: '炼气',
      element: '木',
      hp: 420,
      dps: 9,
      spike: 28,
      spikeInterval: 12,
      tags: ['dot', 'regen'],
      resist: { 木: 0.15 },
      vulnerable: { 火: 0.1 },
      phases: [
        { until: 0.6, mul: { bossDps: 1.1 } },
        { until: 0.3, mul: { bossDps: 1.2 } },
        { until: 0.0, mul: { bossDps: 1.3 } },
      ],
      mechanics: [
        { type: 'slow_drain', target: 'sustain', intensity: 0.12, frequency: 10 },
        { type: 'loop_disrupt', target: 'support', intensity: 0.08, frequency: 12 },
      ],
      desc: '持续缠绕，适合检验续航与稳定性。',
    },
    {
      id: 'boss_xuan_tie',
      name: '玄铁巨兽',
      realm: '筑基',
      element: '金',
      hp: 680,
      dps: 14,
      spike: 45,
      spikeInterval: 10,
      tags: ['armor', 'burst'],
      resist: { 金: 0.2, 水: 0.1 },
      vulnerable: { 火: 0.1 },
      phases: [
        { until: 0.5, mul: { bossDps: 1.15 } },
        { until: 0.2, mul: { bossDps: 1.25 } },
        { until: 0.0, mul: { bossDps: 1.35 } },
      ],
      mechanics: [
        { type: 'port_lock', target: 'skill', intensity: 0.15, frequency: 9 },
        { type: 'loop_disrupt', target: 'main', intensity: 0.1, frequency: 10 },
      ],
      desc: '高护甲与爆发，考验穿透与瞬时承伤。',
    },
    {
      id: 'boss_lie_yan',
      name: '裂焰妖王',
      realm: '金丹',
      element: '火',
      hp: 980,
      dps: 20,
      spike: 70,
      spikeInterval: 9,
      tags: ['burn', 'burst'],
      resist: { 火: 0.2 },
      vulnerable: { 水: 0.15 },
      phases: [
        { until: 0.7, mul: { bossDps: 1.05 } },
        { until: 0.35, mul: { bossDps: 1.2 } },
        { until: 0.0, mul: { bossDps: 1.35 } },
      ],
      mechanics: [
        { type: 'overload', target: 'loop', intensity: 0.12, frequency: 8 },
        { type: 'port_lock', target: 'stat', intensity: 0.1, frequency: 10 },
      ],
      desc: '高爆发+燃烧叠加，考验爆发窗口与解灼。',
    },
    {
      id: 'boss_han_chao',
      name: '寒潮魔相',
      realm: '元婴',
      element: '水',
      hp: 1350,
      dps: 26,
      spike: 85,
      spikeInterval: 8,
      tags: ['slow', 'shield'],
      resist: { 水: 0.2, 金: 0.1 },
      vulnerable: { 土: 0.15 },
      phases: [
        { until: 0.6, mul: { bossDps: 1.1 } },
        { until: 0.3, mul: { bossDps: 1.25 } },
        { until: 0.0, mul: { bossDps: 1.4 } },
      ],
      mechanics: [
        { type: 'shield_invert', target: 'support', intensity: 0.15, frequency: 10 },
        { type: 'loop_disrupt', target: 'main', intensity: 0.1, frequency: 12 },
      ],
      desc: '护盾频繁刷新，适合检验持续输出与削弱。',
    },
    {
      id: 'boss_tu_suo',
      name: '土索巨灵',
      realm: '化神',
      element: '土',
      hp: 1800,
      dps: 32,
      spike: 95,
      spikeInterval: 8,
      tags: ['summon', 'control'],
      resist: { 土: 0.25, 木: 0.1 },
      vulnerable: { 木: 0.1, 金: 0.1 },
      phases: [
        { until: 0.65, mul: { bossDps: 1.1 } },
        { until: 0.35, mul: { bossDps: 1.3 } },
        { until: 0.0, mul: { bossDps: 1.45 } },
      ],
      mechanics: [
        { type: 'port_lock', target: 'mechanic', intensity: 0.15, frequency: 10 },
        { type: 'backlash', target: 'loop', intensity: 0.12, frequency: 9 },
      ],
      desc: '召唤与控制强，考验清场与抗压。',
    },
    {
      id: 'boss_tian_xing',
      name: '天刑主宰',
      realm: '合体',
      element: '无',
      hp: 2400,
      dps: 40,
      spike: 120,
      spikeInterval: 7,
      tags: ['mirror', 'execute'],
      resist: { 金: 0.1, 木: 0.1, 水: 0.1, 火: 0.1, 土: 0.1 },
      vulnerable: {},
      phases: [
        { until: 0.7, mul: { bossDps: 1.1 } },
        { until: 0.4, mul: { bossDps: 1.3 } },
        { until: 0.0, mul: { bossDps: 1.55 } },
      ],
      mechanics: [
        { type: 'mirror', target: 'main', intensity: 0.18, frequency: 9 },
        { type: 'overload', target: 'loop', intensity: 0.15, frequency: 8 },
      ],
      desc: '高压多段伤害，综合强度验证。',
    },
  ];

  global.BossProfiles = BOSS_PROFILES;
})(window);
